name: node2
data-dir: /home/thor/etcd-data/data3
wal-dir: /home/thor/etcd-data/data3
listen-peer-urls: http://localhost:22380
listen-client-urls: http://localhost:22379
initial-advertise-peer-urls: http://localhost:22380
advertise-client-urls: http://localhost:22379
initial-cluster: node2=http://localhost:22379,node0=http://localhost:2380,node1=http://localhost:12379
initial-cluster-token: etcd-cluster
initial-cluster-state: existing
