---
# This is the configuration file for the etcd server.

# Human-readable name for this member.
name: 'n2'

# Path to the data directory.
data-dir: /home/thor/etcd-data/data3

# Path to the dedicated wal directory.
wal-dir: /home/thor/etcd-data/data3

# List of comma separated URLs to listen on for peer traffic.
listen-peer-urls: http://localhost:22380

# List of comma separated URLs to listen on for client traffic.
listen-client-urls: http://localhost:22379

# List of this member's peer URLs to advertise to the rest of the cluster.
# The URLs needed to be a comma-separated list.
initial-advertise-peer-urls: http://localhost:22380

# List of this member's client URLs to advertise to the public.
# The URLs needed to be a comma-separated list.
advertise-client-urls: http://localhost:22379

# Initial cluster configuration for bootstrapping.
initial-cluster: n0=http://localhost:2380,n1=http://localhost:12380,n2=http://localhost:22380

# Initial cluster token for the etcd cluster during bootstrap.
initial-cluster-token: 'etcd-cluster'

# Initial cluster state ('new' or 'existing').
initial-cluster-state: 'existing'

# Reject reconfiguration requests that would cause quorum loss.
strict-reconfig-check: false


client-transport-security:
  # Path to the client server TLS cert file.
  cert-file:

  # Path to the client server TLS key file.
  key-file:

  # Enable client cert authentication.
  client-cert-auth: false

  # Path to the client server TLS trusted CA cert file.
  trusted-ca-file:

  # Client TLS using generated certificates
  auto-tls: false

peer-transport-security:
  # Path to the peer server TLS cert file.
  cert-file:

  # Path to the peer server TLS key file.
  key-file:

  # Enable peer client cert authentication.
  client-cert-auth: false

  # Path to the peer server TLS trusted CA cert file.
  trusted-ca-file:

  # Peer TLS using generated certificates.
  auto-tls: false

# Enable debug-level logging for etcd.
debug: false

logger: zap

# Specify 'stdout' or 'stderr' to skip journald logging even when running under systemd.
log-outputs: [stderr]

# Maximum number of snapshot files to retain (0 is unlimited).
max-snapshots: 0

# Maximum number of wal files to retain (0 is unlimited).
max-wals: 0