name: norse
data-dir: /home/thor/etcd-data/data
wal-dir: /home/thor/etcd-data/data
listen-peer-urls: http://192.168.2.15:2380
listen-client-urls: http://192.168.2.15:2379
initial-advertise-peer-urls: http://192.168.2.15:2380
advertise-client-urls: http://192.168.2.15:2379
initial-cluster: norse=http://192.168.2.15:2380
initial-cluster-token: etcd-cluster
initial-cluster-state: new
